### ISSUE TITLE
Array flatten

### ISSUE THREAD

**Issue by blazingkin** [blazingkin/blz-ospl#39]
Standard library method flat / flatten
[[1, 2], [3,4]].flatten() returns [1, 2, 3, 4]

**Comment by AfaqAnwar** [comment]
Hey, may I work on this issue?

**Comment by AfaqAnwar** [comment]
> Hey, I assume no one else has picked this up. May I work on this issue?

I have completed the implementation.

**Comment by blazingkin** [comment]
Awesome! Thanks for the contribution. I'll get it merged in tomorrow

**Comment by AfaqAnwar** [comment]
> Awesome! Thanks for the contribution. I'll get it merged in tomorrow

I'm so sorry, I'm new to this so contributing is foreign to me. I just realized I have to clone the 2.7 branch place my modified file in there and then build the jars as well. I'll create a new request. 

😆
